# https://github.com/luizdepra/hugo-coder/wiki/Configurations

baseurl = "/"
title = "A cRaftsman's Guide to R"

languageCode = "en-us"
theme = "hugo-coder"
googleAnalytics = "UA-162843697-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

# params -----------------------------------------------------------------------
[params]
    author = "Harel Lustiger"
    description = "A website built through Hugo and blogdown."
    keywords = "Data Science, R Programming"
    info = "Senior Data Scientist"
    avatarurl = "images/logos/profile.jpg"
    footercontent = ""

    dateformat = "2006-01-02"

    hideCredits = true
    hideCopyright = false
    rtl = false
    inverted = false
    custom_css = ["/css/xcode.css", "/css/fonts.css", "/css/main.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

# params.social ----------------------------------------------------------------
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/harell"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/harel_lustiger/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/mean-statistician/"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 2
    url = "https://medium.com/@harell"

# menu.main --------------------------------------------------------------------
[[menu.main]]
    weight = 1
    name = "Tutorials"
    url = "/tutorials/"

[[menu.main]]
    weight = 2
    name = "Talks"
    url = "/talks/"

[[menu.main]]
    weight = 3
    name = "R Packages"
    url = "/packages/"

[[menu.main]]
    weight = 4
    name = "About"
    url = "/about/"
